### ISSUE TITLE
Parameter "includeDescription" not found

### ISSUE THREAD

**Issue by s1lver** [welles/BannerlordCheats#103]
**Modules**:
ButterLib v2.1.3.315545
Harmony v2.2.1.79
Mod Configuration Menu v4 v4.7.0.315545
UIExtenderEx v2.2.0.315545
Birth and Death Options e1.8.0.315545
Cheats v2.10.2.0
CustomBattle e1.8.0.315545
Dedicated Server Dashboard e1.7.2.315545
Multiplayer e1.8.0.315545
Native e1.8.0.315545
Sandbox e1.8.0.315545
SandBox Core e1.8.0.315545
StoryMode e1.8.0.315545

> Exception:
> HarmonyLib.HarmonyException: Patching exception in method virtual TaleWorlds.CampaignSystem.ExplainedNumber TaleWorlds.CampaignSystem.GameComponents.DefaultMobilePartyFoodConsumptionModel::CalculateDailyFoodConsumptionf(TaleWorlds.CampaignSystem.Party.MobileParty party, TaleWorlds.CampaignSystem.ExplainedNumber baseConsumption) ---> System.Exception: Parameter "includeDescription" not found in method virtual TaleWorlds.CampaignSystem.ExplainedNumber TaleWorlds.CampaignSystem.GameComponents.DefaultMobilePartyFoodConsumptionModel::CalculateDailyFoodConsumptionf(TaleWorlds.CampaignSystem.Party.MobileParty party, TaleWorlds.CampaignSystem.ExplainedNumber baseConsumption)
>    at HarmonyLib.MethodPatcher.EmitCallParameter(MethodInfo patch, Dictionary`2 variables, LocalBuilder runOriginalVariable, Boolean allowFirsParamPassthrough, LocalBuilder& tmpObjectVar, List`1 tmpBoxVars)
>    at HarmonyLib.MethodPatcher.<>c__DisplayClass36_0.<AddPostfixes>b__1(MethodInfo fix)
>    at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
>    at HarmonyLib.MethodPatcher.AddPostfixes(Dictionary`2 variables, Boolean passthroughPatches)
>    at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
>    at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
>    at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
>    --- End of inner exception stack trace ---
>    at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
>    at HarmonyLib.PatchClassProcessor.Patch()
>    at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
>    at BannerlordCheats.SubModule.OnGameInitializationFinished(Game game)

**Comment by welles** [comment]
Fixed by update
