### ISSUE TITLE
beta-develop DefaultAgentDecideKilledOrUnconsciousModel

### ISSUE THREAD

**Issue by ridivagyokcso** [welles/BannerlordCheats#107]
Hello.

DefaultAgentDecideKilledOrUnconsciousModel no longer working.
Currently working: SandboxAgentDecideKilledOrUnconsciousModel

PartyOnlyKnockOut, EnemyOnlyKnockOut, FriendlyLordCombatDeathPercentageBattle, EnemyLordCombatDeathChanceMultiplier, EnemyLordCombatDeathPercentageBattle

Thanks.

**Comment by welles** [comment]
Fixed by update
